"""
domains/sales_europe/config.py — generated by setup_domain.py, reviewed manually.
"""

DOMAIN_NAME           = "sales_europe"
DATABASE_NAME         = "sales_europe.db"
DATABASE_PATH         = "domains/sales_europe/db/sales_europe.db"
INPUT_PATH            = "domains/sales_europe/input"
ARCHIVE_PATH          = "domains/sales_europe/input/archive"
PARTITION_KEY         = "order_date"
PARTITION_GRANULARITY = "monthly"   # monthly | weekly | daily
